name: Test Hello World Action

on:
  workflow_run

jobs:
  test:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - run: echo hello world
